### ISSUE TITLE
ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by jacobwilliams** [conda-forge/patchelf-feedstock#41]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

FYI: The `h59595ed_1` release on conda-forge is now causing this error to appear:

```
ELF load command address/offset not properly aligned
```

This problem is discussed at: [patchelf Issue #492](https://github.com/NixOS/patchelf/issues/492)

The `h58526e2_0` build did not have this problem. Both are versioned `0.17.2`.

### Installed packages

```shell
doesn't matter
```

### Environment info

```shell
doesn't matter
```

**Comment by jakirkham** [comment]
Thanks for the report! 🙏

It appears this is due to a recent PR ( https://github.com/conda-forge/patchelf-feedstock/pull/40 ), which added new `0.18.0`

Previously we marked `0.18.0` builds broken ( https://github.com/conda-forge/admin-requests/pull/746 )

Am guessing this is contained to the Linux builds (as we've seen before) and the recently added macOS builds are ok

Could you please send a new PR to `admin-requests` (like the one linked above) marking the Linux packages broken?
